version: '3.9'

services:
  math-service:
    image: math-service
    environment:
      - NATS_SERVER=nats:4222
    build:
      args:
        - workspace=apps/math-service
    depends_on: 
    - 'nats'
  
  echo-service:
    image: echo-service
    environment:
      - NATS_SERVER=nats:4222
    build:
      args:
        - workspace=apps/echo-service
    depends_on: 
    - 'nats'
  
  gateway:
    image: gateway
    environment:
      - NATS_SERVER=nats:4222
      - PORT=80
    build:
      args:
        - workspace=apps/gateway
    expose:
      - '80'
    ports:
      - '80:80'
    depends_on: 
    - 'nats'
    - 'echo-service'
    - 'math-service'

  nats:
    image: nats
    expose:
      - '4222'
      - '8222'
    ports:
      - '4222:4222'
      - '8222:8222'
